# Generated by Django 6.0.5 on 2026-05-19 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'States',
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('pincode_prefix', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.state')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'unique_together': {('name', 'state')},
            },
        ),
    ]
