# Generated by Django 6.0.5 on 2026-05-19 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('order', models.IntegerField(default=0)),
                ('category_type', models.CharField(choices=[('DEF', 'Default'), ('DOC', 'Doctor Speciality')], default='DEF', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'indexes': [models.Index(fields=['name'], name='name_idx'), models.Index(fields=['slug'], name='slug_idx'), models.Index(fields=['parent'], name='parent_idx')],
            },
        ),
    ]
